language: python
python:
  # we want to test our package on several versions of Python
  - 3.6
  - 3.7
  - 3.8

before_install:
  # make depends on poetry
  - pip install poetry

install:
  - make install

  before_script:  # code coverage tool
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make check