[tool.poetry]
name = "AlekcTimc_brain_games"
version = "0.1.1"
description = ""
authors = ["atimchenko <taa@nic.ru>"]
packages = [
  { include = "brain_games" },]
  
[tool.poetry.dependencies]
python = "^3.6"
prompt = "^0.4.1"

[tool.poetry.dev-dependencies]
pylint = "^2.5.2"

[tool.poetry.scripts]
brain-games = "brain_games.scripts.brain_games:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


